from unittest import TestCase

from solvers_2024.solver_08 import SolverImpl


class TestTransformer01(TestCase):
    sut: SolverImpl
    data: str

    @classmethod
    def setUpClass(cls):
        cls.sut = SolverImpl()
        cls.data = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
        """

    def test_transform_1(self):
        # act assert
        self.assertEqual(14, self.sut.solve_part_1(self.data))

    def test_transform_2(self):
        # act assert
        self.assertEqual(34, self.sut.solve_part_2(self.data))
