[tool.poetry]
name = "advent-of-python"
package-mode = false

[tool.poetry.dependencies]
python = "~3.13.1"
pyfunctional = "^1.5.0"
numpy = "^2.1.2"
toolz = "^0.12.0"
typer = "^0.12.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
